# -- 코드를 입력하세요
# SELECT f.FLAVOR, sum(f.TOTAL_ORDER)
# FROM FIRST_HALF f join (SELECT FLAVOR, sum(TOTAL_ORDER) as TOTAL_ORDER
# FROM JULY
# GROUP BY FLAVOR
# ) j
# WHERE f.FLAVOR = j.FLAVOR
# GROUP BY f.FLAVOR
# ORDER BY f.FLAVOR DESC
# LIMIT 3

SELECT f.FLAVOR
FROM FIRST_HALF f JOIN (SELECT FLAVOR, sum(TOTAL_ORDER) as TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) j
ON f.FLAVOR = j.FLAVOR
ORDER BY f.TOTAL_ORDER + j.TOTAL_ORDER DESC
LIMIT 3
